default:
  image: golang:latest
  before_script:
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - task test-full

lint:
  stage: test
  script:
    - make lint
