default:
  image: golang:latest
  before_script: 
    - go install github.com/go-task/task/v3/cmd/task@latest
    
stages:
#  - build
  - test

#build:
#  stage: build
#  script:
#    - task ci:build

test:
  stage: test
  script:
    - task ci:test

lint:
  stage: test
  script:
    - task ci:lint

migration-verify:
  stage: test
  services: [postgres:latest]
  script:
    - task ci:migration-verify
