default:
  image: golang:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - task test-full

lint:
  stage: test
  script:
    - make lint
