default:
  image: golang:latest
  before_script:
    - go install github.com/go-task/task/v3/cmd/task@latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - task test-full

lint:
  stage: test
  script:
    - make lint
