version: "3.8"

services:
  agent:
    image: grafana/agent:v0.28.0
    ports:
      - "14268:14268"
    volumes:
      - "./grafana-agent.yml:/etc/agent/agent.yaml"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test