version: '3'

env:
  ENV: test

dotenv: ['.env', '{{.ENV}}.env']

tasks:
  test:
    cmds:
      - go test --coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out | grep 'total:' | tr -d '[:blank:]\(\)'
  run: go run ./...
  gen: go generate ./...
  lint: golangci-lint run ./...