version: '3'

env:
  ENV: test

dotenv: ['.env', '{{.ENV}}.env']

tasks:
  test:
    cmds:
      - go test ./... -coverprofile cover.out
      - go tool cover -func cover.out
  run: go run ./...
  gen: go generate ./...
  lint: golangci-lint run ./...