.postgres_template: &postgres_service
  services:
    - name: postgres:latest
      alias: postgres-ci
  variables:
    POSTGRES_USER: user-ci
    POSTGRES_PASSWORD: pass-ci
    POSTGRES_HOSTNAME: postgres-ci

default:
  image: golang:1.19-alpine3.15
  before_script: 
    - go install github.com/go-task/task/v3/cmd/task@latest
    
stages:
  - build
  - test
  - generate

build:
  stage: build
  script:
    - task ci:build

test:
  stage: test
  script:
    - task ci:test
  <<: *postgres_service

lint:
  stage: test
  script:
    - task ci:lint

migration-verify:
  stage: test
  script:
    - task ci:migration-verify
  <<: *postgres_service

dependency-graph:
  stage: generate
  script:
    - task ci:depgraph-gen
  artifacts:
    paths:
      - godepgraph.png
    expire_in: never