// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	currency "gitlab.ozon.dev/miromaxxs/telegram-bot/currency"
)

// Baser is an autogenerated mock type for the Baser type
type Baser struct {
	mock.Mock
}

// Base provides a mock function with given fields:
func (_m *Baser) Base() currency.Token {
	ret := _m.Called()

	var r0 currency.Token
	if rf, ok := ret.Get(0).(func() currency.Token); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(currency.Token)
	}

	return r0
}

type mockConstructorTestingTNewBaser interface {
	mock.TestingT
	Cleanup(func())
}

// NewBaser creates a new instance of Baser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBaser(t mockConstructorTestingTNewBaser) *Baser {
	mock := &Baser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
