// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	currency "gitlab.ozon.dev/miromaxxs/telegram-bot/currency"
)

// Converter is an autogenerated mock type for the Converter type
type Converter struct {
	mock.Mock
}

// Convert provides a mock function with given fields: ctx, req
func (_m *Converter) Convert(ctx context.Context, req currency.ConvertReq) (float64, error) {
	ret := _m.Called(ctx, req)

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, currency.ConvertReq) float64); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, currency.ConvertReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewConverter interface {
	mock.TestingT
	Cleanup(func())
}

// NewConverter creates a new instance of Converter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConverter(t mockConstructorTestingTNewConverter) *Converter {
	mock := &Converter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
