// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	currency "gitlab.ozon.dev/miromaxxs/telegram-bot/currency"
)

// Exchange is an autogenerated mock type for the Exchange type
type Exchange struct {
	mock.Mock
}

// Base provides a mock function with given fields:
func (_m *Exchange) Base() currency.Token {
	ret := _m.Called()

	var r0 currency.Token
	if rf, ok := ret.Get(0).(func() currency.Token); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(currency.Token)
	}

	return r0
}

// Convert provides a mock function with given fields: ctx, req
func (_m *Exchange) Convert(ctx context.Context, req currency.ConvertReq) (float64, error) {
	ret := _m.Called(ctx, req)

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, currency.ConvertReq) float64); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, currency.ConvertReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewExchange interface {
	mock.TestingT
	Cleanup(func())
}

// NewExchange creates a new instance of Exchange. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExchange(t mockConstructorTestingTNewExchange) *Exchange {
	mock := &Exchange{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
