// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: service_bot_send.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BotSendClient is the client API for BotSend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotSendClient interface {
	SendReport(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type botSendClient struct {
	cc grpc.ClientConnInterface
}

func NewBotSendClient(cc grpc.ClientConnInterface) BotSendClient {
	return &botSendClient{cc}
}

func (c *botSendClient) SendReport(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, "/pb.BotSend/SendReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotSendServer is the server API for BotSend service.
// All implementations must embed UnimplementedBotSendServer
// for forward compatibility
type BotSendServer interface {
	SendReport(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	mustEmbedUnimplementedBotSendServer()
}

// UnimplementedBotSendServer must be embedded to have forward compatible implementations.
type UnimplementedBotSendServer struct {
}

func (UnimplementedBotSendServer) SendReport(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReport not implemented")
}
func (UnimplementedBotSendServer) mustEmbedUnimplementedBotSendServer() {}

// UnsafeBotSendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotSendServer will
// result in compilation errors.
type UnsafeBotSendServer interface {
	mustEmbedUnimplementedBotSendServer()
}

func RegisterBotSendServer(s grpc.ServiceRegistrar, srv BotSendServer) {
	s.RegisterService(&BotSend_ServiceDesc, srv)
}

func _BotSend_SendReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotSendServer).SendReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BotSend/SendReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotSendServer).SendReport(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotSend_ServiceDesc is the grpc.ServiceDesc for BotSend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotSend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BotSend",
	HandlerType: (*BotSendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendReport",
			Handler:    _BotSend_SendReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_bot_send.proto",
}
