-- create "expenses" table
CREATE TABLE "expenses"
(
    "id"          bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "create_time" timestamptz       NOT NULL,
    "update_time" timestamptz       NOT NULL,
    "created_by"  bigint            NOT NULL,
    "amount"      double precision  NOT NULL,
    "category"    character varying NOT NULL DEFAULT 'UNCATEGORIZED',
    PRIMARY KEY ("id")
);
-- create index "expense_created_by" to table: "expenses"
CREATE INDEX "expense_created_by" ON "expenses" ("created_by");
-- create "personal_settings" table
CREATE TABLE "personal_settings"
(
    "id"          bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "create_time" timestamptz       NOT NULL,
    "update_time" timestamptz       NOT NULL,
    "currency"    character varying NULL DEFAULT 'RUB',
    PRIMARY KEY ("id")
);
